# pullrequest.yml
name: Pull Request Workflow
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  tests:
    needs: linters
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  # report_results:
  #   needs: tests
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:
  #
  #     - name: Check out code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 1
  #         ref: ${{ github.event.pull_request.head.sha }}
  #         persist-credentials: false
  #
  #     - name: Download test results
  #       uses: actions/download-artifact@v3
  #       if: always()
  #       with:
  #         name: test-results
  #
  #     - name: Publish Test Results
  #       uses: EnricoMi/publish-unit-test-result-action@v2
  #       if: always()
  #       with:
  #         files: |
  #           test*results.xml
