# tests.yml
name: Execute tests
on:
  workflow_call:
    secrets:
      ROSA_BURNER_OCM_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      ROSA_BURNER_HYPERSHIFT_SERVICE_CLUSTER:
        required: true
      ROSA_BURNER_ES_URL:
        required: true
jobs:
  test-rosa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subplatform:
        - hypershift
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Download tools
      run: bash utils/download_tools.sh

    - name: Create AWS Config File
      run: |
        echo "[default]" > /tmp/aws_config.ini
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}" >> /tmp/aws_config.ini
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" >> /tmp/aws_config.ini

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: find . -name 'requirements.txt' -exec pip install -r {} \;

    - name: Execute tests
      run: python rosa-burner.py --config-file ./rosa-burner.ini --platform rosa --subplatform ${{matrix.subplatform}}
      env:
        ROSA_BURNER_OCM_TOKEN: ${{ secrets.ROSA_BURNER_OCM_TOKEN }}
        ROSA_BURNER_AWS_ACCOUNT_FILE: "/tmp/aws_config.ini"
        ROSA_BURNER_HYPERSHIFT_SERVICE_CLUSTER: ${{ secrets.ROSA_BURNER_HYPERSHIFT_SERVICE_CLUSTER}}
        ROSA_BURNER_ES_URL: ${{ secrets.ROSA_BURNER_ES_URL}}
        ROSA_BURNER_ES_INDEX: "rosa-burner"

    # - name: Install bats
    #   uses: mig4/setup-bats@v1
    #   with:
    #     bats-version: 1.9.0
    #
    # - name: Execute Tests
    #   working-directory: test
    #   run: |
    #     export PATH=${PATH}:/tmp/
    #     chmod +x /tmp/kube-burner
    #     bats -F pretty -T --report-formatter junit --print-output-on-failure test-k8s.bats
    #   env:
    #     TERM: linux
    #     KIND_VERSION: v0.19.0
    #     K8S_VERSION: ${{matrix.k8s-version}}
    #
    # - name: Upload test results artifact
    #   uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: test-k8s-results
    #     path: test/report.xml
    #
    # - name: Publish Test Report
    #   uses: mikepenz/action-junit-report@v3
    #   if: always()
    #   with:
    #     report_paths: test/report.xml
